// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDGr_yEp_gqMD-i7Ewx8Ic8CjE6y61Zn5o',
    appId: '1:638408212800:web:a8e67d0299a981b1c2faa5',
    messagingSenderId: '638408212800',
    projectId: 'testproject418787141',
    authDomain: 'testproject418787141.firebaseapp.com',
    storageBucket: 'testproject418787141.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAbvC9uHPZA1qCeFqUjimCX6t0_2sjkBxY',
    appId: '1:638408212800:android:412f7a91af73b160c2faa5',
    messagingSenderId: '638408212800',
    projectId: 'testproject418787141',
    storageBucket: 'testproject418787141.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCYZNr-Ryf94kfLvsXW3SbnvYFIkQIx3kI',
    appId: '1:638408212800:ios:459800295e9ef5d5c2faa5',
    messagingSenderId: '638408212800',
    projectId: 'testproject418787141',
    storageBucket: 'testproject418787141.firebasestorage.app',
    iosBundleId: 'com.example.testProject',
  );
}
